#ifndef TORC_TORCMDS_H
#define TORC_TORCMDS_H

#include "torc.h"

#define TORC_SETCONF "SETCONF"
#define TORC_RESETCONF "RESETCONF"
#define TORC_GETCONF "GETCONF"
#define TORC_SETEVENTS "SETEVENTS"
#define TORC_SAVECONF "SAVECONF"
#define TORC_SIGNAL "SIGNAL"
#define TORC_MAPADDRESS "MAPADDRESS"
#define TORC_GETINFO "GETINFO"
#define TORC_EXTENDCIRCUIT "EXTENDCIRCUIT"
#define TORC_SETCIRCUITPURPOSE "SETCIRCUITPURPOSE"
#define TORC_SETROUTERPURPOSE "SETROUTERPURPOSE"
#define TORC_ATTACHSTREAM "ATTACHSTREAM"
#define TORC_POSTDESCRIPTOR "POSTDESCRIPTOR"
#define TORC_REDIRECTSTREAM "REDIRECTSTREAM"
#define TORC_CLOSESTREAM "CLOSESTREAM"
#define TORC_CLOSECIRCUIT "CLOSECIRCUIT"
#define TORC_USEFEATURE "USEFEATURE"
#define TORC_RESOLVE "RESOLVE"
#define TORC_PROTOCOLINFO "PROTOCOLINFO"
#define TORC_LOADCONF "LOADCONF"
#define TORC_TAKEOWNERSHIP "TAKEOWNERSHIP"
#define TORC_AUTHCHALLENGE "AUTHCHALLENGE"
#define TORC_DROPGUARDS "DROPGUARDS"
#define TORC_HSFETCH "HSFETCH"
#define TORC_ADD_ONION "ADD_ONION"
#define TORC_DEL_ONION "DEL_ONION"
#define TORC_HSPOST "HSPOST"
#define TORC_ONION_CLIENT_AUTH_ADD "ONION_CLIENT_AUTH_ADD"
#define TORC_ONION_CLIENT_AUTH_REMOVE "ONION_CLIENT_AUTH_REMOVE"
#define TORC_ONION_CLIENT_AUTH_VIEW "ONION_CLIENT_AUTH_VIEW"
#define TORC_DROPOWNERSHIP "DROPOWNERSHIP"
#define TORC_DROPTIMEOUTS "DROPTIMEOUTS"

#ifdef __cplusplus
extern "C" {
#endif

// AUTHENTICATE and QUIT command handled in torc.h
// the rest of the commands will be implemented here

// TODO: PROTOCOLINFO VERSION PARSING (not important)
typedef struct {
    char* version;
    char* auth_methods;
    char* cookie_file;
} torc_protocol_info_response;

torc_protocol_info_response torc_send_protocol_info_command(torc* controller, torc_command* command);

#ifdef __cplusplus
}
#endif

#endif //TORC_TORCMDS_H
